# Generated by Django 3.2.19 on 2023-05-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
