# Generated by Django 3.2.19 on 2023-06-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='UserProfile', max_length=250),
            preserve_default=False,
        ),
    ]
