# Generated by Django 3.2.19 on 2023-05-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['created_at']},
        ),
    ]
