# Generated by Django 3.2.19 on 2023-05-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230523_2125'),
        ('boosts', '0002_auto_20230527_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='profiles.profile'),
        ),
    ]
