# Generated by Django 3.2.19 on 2023-05-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('experiences', '0002_auto_20230524_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
