# Generated by Django 3.2.19 on 2023-05-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230523_2125'),
        ('experiences', '0003_experience_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.profile'),
        ),
    ]
