# Generated by Django 3.2.19 on 2023-05-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230523_2125'),
        ('recommendation_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='sender',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('profile', 'receiver')},
        ),
    ]
