# Generated by Django 3.2.19 on 2023-05-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20230527_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='profile',
        ),
    ]
