# Generated by Django 3.2.19 on 2023-05-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
