# Generated by Django 3.2.19 on 2023-05-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_delete_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
    ]
