# Generated by Django 3.2.19 on 2023-05-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_alter_relationship_options'),
        ('recommendations', '0002_rename_experience_recommendation_related_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relationships.relationship'),
        ),
    ]
