# Generated by Django 3.2.19 on 2023-05-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230523_2125'),
        ('recommendations', '0003_recommendation_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_sent', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to='profiles.profile'),
        ),
    ]
