# Generated by Django 3.2.19 on 2023-05-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230523_2125'),
        ('experiences', '0004_alter_experience_profile'),
        ('recommendations', '0005_alter_recommendation_related_experience'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('profile', 'receiver', 'related_experience')},
        ),
    ]
